FROM python:3.11

COPY requirements.txt .

RUN pip install -r requirements.txt

WORKDIR /app

COPY ./app .

# ARG SWITCHBOT_TOKEN
# ARG SWITCHBOT_SECRET

# ENV SWITCHBOT_TOKEN=/${SWITCHBOT_TOKEN}
# ENV SWITCHBOT_SECRET=/${SWITCHBOT_SECRET}

EXPOSE 8000