version: '3'
services:
  app:
    container_name: switchbot_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./requirements.txt:/requirements.txt
    env_file:
      - .env
    tty: true
